# Generated by Django 4.2.11 on 2024-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('text_color', models.CharField(max_length=7)),
                ('board_color', models.CharField(max_length=7)),
                ('posted_date', models.DateField()),
            ],
        ),
    ]
