# Generated by Django 4.2.11 on 2024-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stickynote_delete_clipboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
