# Generated by Django 4.2.11 on 2024-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
