# Generated by Django 4.2.11 on 2024-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stickynote_dislikes_stickynote_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
