# Generated by Django 4.2.11 on 2024-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_stickynote_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='dislikes',
            new_name='angries',
        ),
        migrations.RenameField(
            model_name='stickynote',
            old_name='likes',
            new_name='loves',
        ),
        migrations.AddField(
            model_name='stickynote',
            name='cries',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='wows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
