# Generated by Django 4.2.11 on 2024-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_dislikes_stickynote_angries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='content_font_index',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='nickname_font_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
