# Generated by Django 4.2.11 on 2024-06-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stickynote_content_font_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='angries',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='content_font_index',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='cries',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='loves',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='nickname_font_index',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='wows',
        ),
    ]
